buildpack: https://github.com/pkgr/pkgr-source-buildpack
targets:
  ubuntu-18.04: 
    build_dependencies: &debian_build_deps
      - libsqlite3-dev
      - make
      - curl
      - gawk
      - freetds-dev
      - libzip-dev
  ubuntu-16.04:
    build_dependencies:
      <<: *debian_build_deps
  debian-9:
    build_dependencies:
      <<: *debian_build_deps
  debian-8:
    build_dependencies:
      <<: *debian_build_deps
