debian-deps: &debiandeps
  - libsqlite3-dev
  - make
  - curl
  - gawk
  - freetds-dev
  - libzip-dev


buildpack: https://github.com/pkgr/pkgr-source-buildpack
targets:
  ubuntu-18.04: 
    build_dependencies:
      <<: *debiandeps
  ubuntu-16.04:
    build_dependencies:
      <<: *debiandeps
  debian-9:
    build_dependencies:
      <<: *debiandeps
  debian-8:
    build_dependencies:
      <<: *debiandeps
