cli: bin/pgloader
buildpack: https://github.com/pkgr/pkgr-source-buildpack
targets:
  ubuntu-18.04: 
    default_dependencies: false
    build_dependencies:
      - freetds-dev
      - libzip-dev
    dependencies:
      - gawk
  ubuntu-16.04:
    default_dependencies: false
    build_dependencies:
      - freetds-dev
      - libzip-dev
    dependencies:
      - gawk
  debian-10:
    default_dependencies: false
    build_dependencies:
      - freetds-dev
      - libzip-dev
    dependencies:
      - gawk
  debian-9:
    default_dependencies: false
    build_dependencies:
      - freetds-dev
      - libzip-dev
    dependencies:
      - gawk
  debian-8:
    default_dependencies: false
    build_dependencies:
      - freetds-dev
      - libzip-dev
    dependencies:
      - gawk
  centos-7:
    default_dependencies: false
    build_dependencies:
      - libzip-devel
      - freetds-devel
    dependencies:
      - gawk
  sles-12:
    default_dependencies: false
    build_dependencies:
      - libzip-devel
      - freetds-devel
    dependencies:
      - gawk
